package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.HeadlessException;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;

import control.Main;
import control.UpdateData;
import model.Player;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.io.IOException;
//register class
public class RegisterFrame extends JFrame {

	private JPanel contentPane;
    
	
	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					RegisterFrame frame = new RegisterFrame();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the frame.
	 */
	public RegisterFrame() {
		  initComponents();
	        this.setResizable(false);
	       
	        username.setForeground(Color.gray);
	      
	        
	        Font font1 = new Font("Serif", Font.BOLD, 20);
	        username.setHorizontalAlignment(SwingConstants.CENTER);  
	        username.setFont(font1);
	         
	        password.setHorizontalAlignment(SwingConstants.CENTER);  
	        password.setFont(font1);
	         
	        username.setText("User Name");
	        
	        password.setForeground(Color.gray);
	        password.setText("Password");
	        
	        
	        username.setEditable(true);
	        password.setEditable(true);
	       
	        
	     
	        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

	    	   this.addWindowListener(new java.awt.event.WindowAdapter() {
	    	       @Override
	    	       public void windowClosing(java.awt.event.WindowEvent windowEvent) {
	    	           
	    	         int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?","message",JOptionPane.YES_NO_OPTION);
	    	           if (reply == JOptionPane.YES_OPTION) {
	    	              Menu m=new Menu(control.Main.file,control.Main.dataFile);
	    	              m.setVisible(true);
	    	              setVisible(false);
	    	           }  
	    	       }
	    	   });
	          
	            
	            
	            
	           
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        logoTitle = new JLabel();
	        back = new JLabel();
	        username = new JTextField();
	        username.addFocusListener(new FocusAdapter() {
	        	@Override
	        	public void focusLost(FocusEvent e) {
	        		username.setForeground(Color.gray);
	                if(username.getText().length() <1)
	                    username.setText("User Name");
	                else
	                     username.setForeground(Color.black);
	        	}
	        	@Override
	        	public void focusGained(FocusEvent e) {
	        		username.setForeground(Color.black);
	        	       
	        	       if(username.getText().equals("User Name"))
	        	             username.setText("");
	        	}
	        	
	        });
	        password = new JTextField();
	        password.addFocusListener(new FocusAdapter() {
	        	@Override
	        	public void focusLost(FocusEvent e) {
	        		password.setForeground(Color.gray);
	                if(password.getText().length() <1)
	                	password.setText("Password");
	                else
	                	password.setForeground(Color.black);
	        	}
	        	@Override
	        	public void focusGained(FocusEvent e) {
	        		password.setForeground(Color.black);
	        	       
	        	       if(password.getText().equals("Password"))
	        	    	   password.setText("");
	        	}
	        	
	        });
	   
	        imgADD = new JLabel();
	        doneLabel = new JLabel();
	        jLabel1 = new JLabel();

	      
	        setTitle("Monopoly Game");
	        setMaximumSize(new java.awt.Dimension(1200, 600));
	        setMinimumSize(new java.awt.Dimension(1200, 600));
	        setPreferredSize(new java.awt.Dimension(1200, 600));
	        getContentPane().setLayout(null);

	        logoTitle.setBackground(new java.awt.Color(255, 255, 255));
	        logoTitle.setFont(new java.awt.Font("Gabriola", 2, 115)); // NOI18N
	        logoTitle.setText("Monopoly Game");
	        getContentPane().add(logoTitle);
	        logoTitle.setBounds(120, 0, 660, 167);

	        back.setBackground(new java.awt.Color(255, 255, 255));
	        back.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
	        back.setForeground(new java.awt.Color(255, 255, 255));
	       
	        
	       
	        getContentPane().add(back);
	        back.setBounds(110, 160, 70, 80);

	      
	        getContentPane().add(username);
	        username.setBounds(215, 169, 360, 60);

	     
	        getContentPane().add(password);
	        password.setBounds(215, 254, 360, 60);

	        
	        

	       
	        btnNewButton = new JButton("New button");
	        btnNewButton.addActionListener(new ActionListener() {
	        	public void actionPerformed(ActionEvent e) {
	        		CheakDeatil();
	        		
	        	}
	        });
	        btnNewButton.setIcon(new ImageIcon(RegisterFrame.class.getResource("/images/loginbtn.jpg")));
	        btnNewButton.setBounds(309, 432, 122, 45);
	        getContentPane().add(btnNewButton);
	      

	        jLabel1.setIcon(new ImageIcon(RegisterFrame.class.getResource("/images/login.jpg"))); // NOI18N
	        getContentPane().add(jLabel1);
	        jLabel1.setBounds(0, 0, 1207, 565);

	        pack();
	        setLocationRelativeTo(null);
	    }// </editor-fold>                        

	                                     

	                                     

	                                    

	                    

	   
	                                        

	    private void CheakDeatil() {                                       


	        if( username.getText().length()<1 || username.getText().equals("User Name") || password.getText().length()<1 || password.getText().equals("Password")){
	            JOptionPane.showMessageDialog(rootPane, "Please fill all the fields");
	        }
	        
	        UpdateData updateSystem = UpdateData.getInstance();
	           
	           if(updateSystem.checkPlayerUserName(username.getText())){
	            	JOptionPane.showMessageDialog(rootPane, "User name already exist! Please choose another name");
	            }
	           
	        else{
	            String user= username.getText();
	            String pass = password.getText();
	          
	            
	            
	           
	           
	           Player p=new Player(user,pass);
	           
	           try {
				if(updateSystem.addNewUser(p)){
				        JOptionPane.showMessageDialog(rootPane, "User Successfully added!");
				        this.setVisible(false);
				        Menu mf = new Menu(control.Main.file,control.Main.dataFile);
				        mf.setVisible(true);
				        this.setVisible(false);
				   }else{
				       JOptionPane.showMessageDialog(rootPane, "Failed to add new user - a User with the same username already exist");
				   }
			} catch (HeadlessException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
	          
	            
	        }
	        
	        
	    }                                      

	 
	    

	    // Variables declaration - do not modify                     
	    private JLabel back;
	    private JLabel doneLabel;
	    private JLabel imgADD;
	    private JLabel jLabel1;
	    private JLabel logoTitle;
	    private JTextField password;
	    private JTextField username;
	   // private JTextField id;
	    private JButton btnNewButton;
	    
	    // End of variables declaration                   
	}


